name: deploydodo-dev
services:
  dododb:
    image: postgres:15.18-alpine3.24
    environment:
      POSTGRES_USER: deploydodo
      POSTGRES_PASSWORD: deploydodo
      POSTGRES_DB: deploydodo
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U deploydodo -d deploydodo']
      interval: 2s
      timeout: 3s
      retries: 10
    ports:
      - 5432:5432
    volumes:
      - dododb-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  dododb-data:
