[config]
default_to_workspace = false

[tasks.backend]
description = "Run the backend server"
command = "cargo"
args = ["run", "-p", "backend"]

[tasks.build-backend-debug]
description = "Build the backend server"
command = "cargo"
args = ["build", "-p", "backend"]

[tasks.build-backend]
description = "Build the backend server"
command = "cargo"
args = ["build", "--release", "-p", "backend"]

[tasks.build-backend-linux]
description = "Build the backend server for linux"
command = "cargo"
args = [
    "build",
    "--release",
    "-p", "backend",
    "--target", "aarch64-unknown-linux-musl",
    "--config", "target.aarch64-unknown-linux-musl.linker=\"aarch64-unknown-linux-gnu-gcc\""
]

[tasks.frontend]
description = "Run the frontend development server"
dependencies = ["generate-schema"]
command = "npm"
args = ["run", "dev", "--prefix", "frontend"]

[tasks.build-frontend]
description = "Build the frontend development server"
dependencies = ["generate-schema"]
command = "npm"
args = ["run", "build", "--prefix", "frontend"]

[tasks.migration]
description = "Add a new database migration"
command = "sqlx"
args = ["migrate", "add", "-t", "-r", "${@}"]
cwd = "backend"

[tasks.migrate]
description = "Run database migrations"
command = "sqlx"
args = ["migrate", "run"]
cwd = "backend"

[tasks.undo-migrate]
description = "Revert the last database migration"
command = "sqlx"
args = ["migrate", "revert"]
cwd = "backend"

[tasks.download-schema]
description = "Saves the OpenApi schema from the backend"
command = "cargo"
args = ["run", "-p", "backend", "--bin", "openapi_gen"]

[tasks.generate-schema]
description = "Generate the frontend API schema"
dependencies = ["download-schema"]
command = "npm"
args = ["run", "generate:api", "--prefix", "frontend"]

[tasks.deploy-dev-db]
description = "Deploy the dev DB to port 5432"
command = "docker"
args = ["compose", "-f", "dev.docker-compose.yaml", "up", "-d"]

[tasks.dev]
description = "Run backend and frontend concurrently"
dependencies = ["deploy-dev-db"]
run_task = { name = ["backend", "frontend"], parallel = true }

[tasks.build]
dependencies = ["build-backend", "build-frontend"]

[tasks.build-debug]
dependencies = ["build-backend-debug", "build-frontend"]

[tasks.compose]
command = "docker"
args = ["compose", "-f", "staging.docker-compose.yaml", "up", "-d", "--build"]
