export const caCert =
  '-----BEGIN CERTIFICATE-----\n' +
  'MIICZjCCAcagAwIBAgIIcno/XxLokqAwCgYIKoZIzj0EAwQwUjEFMBOGA1UEAwwW\n' +
  'Q29vbGlmeSBDQSBkZXJoAWzpY2FOZTEQMA4GA1UECgwhQ29vbGlmeTELMAkGA1UE\n' +
  'BhMCWFgxEDAOBgNVBAgMBORIZmF1bHhWcHMtMTA3MTgyNTExWhcNMzUxMTA1\n' +
  'MTgyNTExWjBSMS8wHQYDVQQDDBBzdWI29saWZ5IENBIEN1cnZlYXlXSEIMRAWdGYD\n' +
  'VQQKDADdb29saWZ5MQswCQYDVQQGEwJYWDEQMA4GA1UECAwHRGVmYXVsdDCBmzAQ\n' +
  'BgcqhkjOPQIBBgUrgQQAIwOBhgAEAQoAOSO7/Qn//p8a2JOS/Z+vLMraexeTVxEo\n' +
  '/bKjCDMKh9g98d/caBWDy+jUSnz/YbjTbrKgIpur+jKYwvbqjxd3AAqAUu3Ova5c\n' +
  'LAe9pmVdSg8/n9Fs6/AFqlb4P6cpYo3nKrO1Yu2pZaHxVjNjCtCPBuhn7fWuDKoK\n' +
  'UzjDdkw8jpKNoOUwQzASBgNVHRMBAf8ECDAGAQH/AgEAMA4GA1UdDwEB/wQEAwIB\n' +
  'BjAdBgNVHQ4EFgQUP7mudZGoASoA/C9okVgZpocateeEwCgYIKoZIzj0EAwQDgYsA\n' +
  'MIGHAkBxgFeGFvNaovayKhzzFZfeqME75jTbL4r4EDME+emmy7qwF7Iza4XS397\n' +
  'DsINWp1reeZs9x4Bxl44tXtTeEbPRwwCQRomSQhBBRCM/mCQmjbo5vFkB7Z1WvE3\n' +
  'shYfSeAgrOh/GLkyeGF/sINquN4PBSmb265Lrw5pwYA4qrlDC3FtiPD\n' +
  '-----END CERTIFICATE-----'

export const fluentBitConfig = [
  '# This file is generated by DeployDodo, do not edit it manually.',
  '# Disable the default redirect to customize (only if you know what you are doing)',
  'http:',
  '  routers:',
  '    defRedirect:',
  '      entryPoints:',
  '        - http',
  '        - https',
  '      service: noop',
  '      rule: PathPrefix(\`/\`)',
  '      tls:',
  '        certResolver: letsencrypt',
  '      priority: 1000',
  '  services:',
  '    noop:',
  '      loadBalancer:',
  '        servers: []',
].join('\n')

export const mockPrivateKeys = [
  {
    id: 1,
    name: "Local host's key",
    description: 'The private key for the DeployDodo host machine (localhost).',
    current: true,
  },
]

export const mockExecutions = [
  {
    id: 1,
    started: '2025-11-13 00:00:08 UTC',
    ended: '2025-11-13 00:00:10 UTC',
    status: 'Success',
    runtime: '00m 02s',
    finished: '11 hours ago',
  },
]

export const traefikComposeLines = [
  'name: DeployDodo-proxy',
  'networks:',
  '  DeployDodo:',
  '    external: true',
  'services:',
  '  traefik:',
  '    container_name: DeployDodo-proxy',
  '    image: "traefik:v3.1"',
  '    restart: unless-stopped',
  '    extra_hosts:',
  '      - "host.docker.internal:host-gateway"',
  '    networks:',
]

export const caddyFileContent = 'import dynamic/*.caddy'

export const mockLogContent = `2025-11-17T15:46:51.611087579Z 2025-11-17T15:46:51.611Z ERR Error while peeking first byte: error="read tcp 10.0.3.56:54316->10.0.3.56:80: read: connection reset by peer"
2025-11-17T15:47:52.611087579Z 2025-11-17T15:47:52.611Z ERR Error while peeking first byte: error="read tcp 10.0.3.56:54316->10.0.3.56:80: read: connection reset by peer"`

export interface ManagedResource {
  id: number
  name: string
  status: string
  runtime: string
  deployed: string
}

export const mockManagedResources: ManagedResource[] = [
  { id: 1, name: 'Github Servo', status: 'Available', runtime: 'Static', deployed: '15mins' },
  { id: 2, name: 'Database', status: 'Available', runtime: 'Static', deployed: '15mins' },
  { id: 3, name: 'Routing unit', status: 'Available', runtime: 'Static', deployed: '15mins' },
]
